#!/usr/bin/env python

import os
import fcntl
import shutil
import sys

file_ = os.path.expanduser('~/.my_history')
f = open(file_,'r')
lines = list(f.readlines())
f.close()

myset = set(lines)

file_bash = os.path.expanduser('~/.bash_history')
f = open(file_bash,'r')
lines += list(f.readlines())
f.close()

lineset = set(lines)
diff = lineset - myset
if len(diff) == 0:
	sys.exit(0)
sys.stdout.write("+")
newlist = []
lines.reverse()
for line in lines:
	if line in lineset:
		newlist.append(line)
		lineset.remove(line)
f = open(file_, 'w')
fcntl.flock(f.fileno(), fcntl.LOCK_EX)
newlist.reverse()
count = 0
for line in newlist:
	count += 1
	if count > 5000:
		break
	f.write(line)
fcntl.flock(f.fileno(), fcntl.LOCK_UN)
f.close()
shutil.copyfile(file_, file_bash)
sys.exit(0)
